# fly.toml app configuration file generated for nestjs-api on 2023-11-22T08:39:22+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "nestjs-api"
primary_region = "otp"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
